version: '3.7'
services:
  regional_manager:
    container_name: regional_manager
    image: regional_manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 0.0.0.0:7654:7654
    env_file:
      - app/.env