version: '3.7'
services:
  regional_master:
    container_name: regional_master
    image: regional_master:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 0.0.0.0:7654:7654/tcp